### ISSUE TITLE
How to return the selected images?

### ISSUE THREAD

**Issue by michaelzhuang06** [ibrahimyilmaz7/MultipleImagePicker#1]
It is a great example! 

I am new to swfitUI , may I ask how to return selected image? And by the way, if there is not "MultipleImagePicker" on the example, only Button action , the image won't show on the sheet. Thanks!

Michael

**Comment by ibrahimyilmaz7** [comment]
You can use this one:

https://github.com/ibrahimyilmaz7/MultipleImagePicker/blob/1b03a2a9953de88256e0c696c0031b8773a4becb/MultipleImagePicker/MultipleImagePicker/ContentView.swift#L17-L20
